### ISSUE TITLE
How precise is this?

### ISSUE THREAD

**Issue by infinite-happiness** [MikeDenisov/TithiTools#1]
Hi!

Very nice that you have created a Tithi calculator.

It would be nice to know how accurate this calculator is.

Thank you!

**Comment by cappuccinopirate** [comment]
Hi! To estimate accuracy, I have to split it into two parts:

1. Finding angles between the Sun, Moon, and Earth at a given time.
To do that, the calculator relies on the [CoordinateSharp](https://github.com/Tronald/CoordinateSharp) data. I'm not sure about the precision on their side, but it seems quite accurate.
2. Searching for the exact moments when the angles between these bodies are exactly 12 degrees. This is the tricky part, which is done using a binary search, and it gives very close results. This is where the precision argument plays in - it's basically a balance between precision and performance.

Overall, with the online sources I compared it with, it was a matter of minutes difference. However, we don't know how other sources are doing their calculations, right?
